[PHP]
memory_limit = 256M
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

[xdebug]
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.log = /var/www/html/xdebug.log
